// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BasicArrow: typeof import('./../src/components/Basic/src/BasicArrow.vue')['default']
    BasicHelp: typeof import('./../src/components/Basic/src/BasicHelp.vue')['default']
    BasicModal: typeof import('./../src/components/modal/src/BasicModal.vue')['default']
    BasicTable: typeof import('./../src/components/BasicTable/index.vue')['default']
    BasicTitle: typeof import('./../src/components/Basic/src/BasicTitle.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    ModalClose: typeof import('./../src/components/modal/src/components/ModalClose.vue')['default']
    ModalFooter: typeof import('./../src/components/modal/src/components/ModalFooter.vue')['default']
    ModalHeader: typeof import('./../src/components/modal/src/components/ModalHeader.vue')['default']
    ModalWrapper: typeof import('./../src/components/modal/src/components/ModalWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./../src/components/Table/index.vue')['default']
    TableAction: typeof import('./../src/components/BasicTable/TableAction.vue')['default']
    TableForm: typeof import('./../src/components/BasicTable/TableForm.vue')['default']
    Tree: typeof import('../src/components/Form/Tree/index.ts')['default']
  }
}
